service: dashboard
plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
    getDashboard:
      handler: modules/summary/controller.hello
      events:
      - http:
         path: hello
         method: get
  
    addDashboard:
      handler: modules/summary/controller.hello
      events:
      - http:
         path: hello
         method: post
