service: dashboard
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
    server:
      handler: index.handler
      events:
      - http: ANY /
      - https: ANY /
